# .readthedocs.yml
# Read the Docs configuration file

# Details
# - https://docs.readthedocs.io/en/stable/config-file/v2.html
# - https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

  # https://docs.readthedocs.io/en/stable/build-customization.html#extend-the-build-process
  jobs:
    post_install:
      # setuptools has been downgraded to 58.2.0, so upgrade again.
      - pip install --upgrade setuptools
      - pip install uv
      # Install project's dependencies.
      # see https://github.com/python-poetry/poetry/issues/9025
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH .github/workflows/install.sh docs

# Build documentation in the docs/ directory with Sphinx
mkdocs:
  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
