site_name: Wetterdienst
site_url: !ENV READTHEDOCS_CANONICAL_URL
site_author: earthobservations
site_description: Open weather data for humans.
copyright: Copyright (c) 2018 - 2024 earthobservations
repo_name: earthobservations/wetterdienst
repo_url: https://github.com/earthobservations/wetterdienst
theme:
  name: material
  # https://squidfunk.github.io/mkdocs-material/customization/
  custom_dir: docs/overrides  # for RTD
  features:
    - navigation.indexes
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
# RTD addons https://docs.readthedocs.io/en/stable/intro/mkdocs.html
extra_css:
  - stylesheets/readthedocs.css
extra_javascript:
  - javascript/readthedocs.js
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
plugins:
  - search
  - mkdocstrings:
      default_handler: python
nav:
  - Overview: index.md
  - Data:
    - Overview: data/overview.md
    - Parameters: data/parameters.md
    - Providers:
      - DWD:
        - data/provider/dwd/index.md
        - DMO:
          - data/provider/dwd/dmo/index.md
          - hourly: data/provider/dwd/dmo/hourly.md
        - Mosmix:
          - data/provider/dwd/mosmix/index.md
          - hourly: data/provider/dwd/mosmix/hourly.md
        - Observation:
          - data/provider/dwd/observation/index.md
          - 1_minute: data/provider/dwd/observation/1_minute.md
          - 5_minutes: data/provider/dwd/observation/5_minutes.md
          - 10_minutes: data/provider/dwd/observation/10_minutes.md
          - hourly: data/provider/dwd/observation/hourly.md
          - subdaily: data/provider/dwd/observation/subdaily.md
          - daily: data/provider/dwd/observation/daily.md
          - monthly: data/provider/dwd/observation/monthly.md
          - annual: data/provider/dwd/observation/annual.md
        - Radar: data/provider/dwd/radar.md
        - Road:
          - data/provider/dwd/road/index.md
          - 15_minutes: data/provider/dwd/road/15_minutes.md
      - EA:
        - data/provider/ea/index.md
        - Hydrology:
          - data/provider/ea/hydrology/index.md
          - 6_hours: data/provider/ea/hydrology/6_hours.md
          - 15_minutes: data/provider/ea/hydrology/15_minutes.md
          - daily: data/provider/ea/hydrology/daily.md
      - Eaufrance:
        - data/provider/eaufrance/index.md
        - Hubeau:
          - data/provider/eaufrance/hubeau/index.md
          - dynamic: data/provider/eaufrance/hubeau/dynamic.md
      - ECCC:
        - data/provider/eccc/index.md
        - Observation:
          - data/provider/eccc/observation/index.md
          - hourly: data/provider/eccc/observation/hourly.md
          - daily: data/provider/eccc/observation/daily.md
          - monthly: data/provider/eccc/observation/monthly.md
          - annual: data/provider/eccc/observation/annual.md
      - Geosphere:
        - data/provider/geosphere/index.md
        - Observation:
          - data/provider/geosphere/observation/index.md
          - 10_minutes: data/provider/geosphere/observation/10_minutes.md
          - hourly: data/provider/geosphere/observation/hourly.md
          - daily: data/provider/geosphere/observation/daily.md
          - monthly: data/provider/geosphere/observation/monthly.md
      - IMGW:
        - data/provider/imgw/index.md
        - Hydrology:
          - data/provider/imgw/hydrology/index.md
          - daily: data/provider/imgw/hydrology/daily.md
          - monthly: data/provider/imgw/hydrology/monthly.md
        - Meteorology:
          - data/provider/imgw/meteorology/index.md
          - daily: data/provider/imgw/meteorology/daily.md
          - monthly: data/provider/imgw/meteorology/monthly.md
      - NOAA:
        - data/provider/noaa/index.md
        - GHCN:
          - data/provider/noaa/ghcn/index.md
          - hourly: data/provider/noaa/ghcn/hourly.md
          - daily: data/provider/noaa/ghcn/daily.md
      - NWS:
        - data/provider/nws/index.md
        - Observation:
          - data/provider/nws/observation/index.md
          - hourly: data/provider/nws/observation/hourly.md
      - WSV:
        - data/provider/wsv/index.md
        - Pegel:
          - data/provider/wsv/pegel/index.md
          - dynamic: data/provider/wsv/pegel/dynamic.md
  - Usage:
    - usage/python-api.md
    - usage/python-examples.md
    - usage/cli.md
    - usage/restapi.md
    - usage/explorer.md
    - usage/docker.md
    - usage/settings.md
    - usage/units.md
  - Library:
    - library/api.md
    - library/machinery.md
    - library/core.md
  - License: license.md
  - Contribution:
    - contribution/development.md
    - contribution/services.md
  - known_issues.md
  - changelog.md
