""" mapping from german column names to english column names"""
ORIG_STATION_ID_NAME = "STATIONS_ID"
ORIG_DATE_NAME = "MESS_DATUM"
ORIG_FROM_DATE_NAME = "VON_DATUM"
ORIG_TO_DATE_NAME = "BIS_DATUM"
ORIG_STATIONHEIGHT_NAME = "STATIONSHOEHE"
ORIG_LAT_NAME = "GEOBREITE"
ORIG_LAT_ALT_NAME = "GEOGR.BREITE"
ORIG_LON_NAME = "GEOLAENGE"
ORIG_LON_ALT_NAME = "GEOGR.LAENGE"
ORIG_STATIONNAME_NAME = "STATIONSNAME"
ORIG_STATE_NAME = "BUNDESLAND"

STATION_ID_NAME = "STATION_ID"
DATE_NAME = "DATE"
FROM_DATE_NAME = "FROM_DATE"
TO_DATE_NAME = "TO_DATE"
STATIONHEIGHT_NAME = "STATIONHEIGHT"
LAT_NAME = "LAT"
LON_NAME = "LON"
STATIONNAME_NAME = "STATIONNAME"
STATE_NAME = "STATE"

GERMAN_TO_ENGLISH_COLUMNS_MAPPING = {ORIG_STATION_ID_NAME: STATION_ID_NAME,
                                     ORIG_DATE_NAME: DATE_NAME,
                                     ORIG_FROM_DATE_NAME: FROM_DATE_NAME,
                                     ORIG_TO_DATE_NAME: TO_DATE_NAME,
                                     ORIG_STATIONHEIGHT_NAME: STATIONHEIGHT_NAME,
                                     ORIG_LAT_NAME: LAT_NAME,
                                     ORIG_LAT_ALT_NAME: LAT_NAME,
                                     ORIG_LON_NAME: LON_NAME,
                                     ORIG_LON_ALT_NAME: LON_NAME,
                                     ORIG_STATIONNAME_NAME: STATIONNAME_NAME,
                                     ORIG_STATE_NAME: STATE_NAME}
FILENAME_NAME = "FILENAME"
HAS_FILE_NAME = "HAS_FILE"
FILEID_NAME = "FILEID"
