# Copyright (C) 2018-2025, earthobservations developers.
# Distributed under the MIT License. See LICENSE for more info.
"""DWD phenology metadata.

The DWD phenological network records, for one plant at one station, the day of the year on which
a given developmental phase was reached -- first flowering, leaf unfolding, harvest. Observations
come from two reporter groups: the *Jahresmelder* (annual reporters), who submit their whole
season at the end of the year, and the *Sofortmelder* (immediate reporters), who report a smaller
set of phases within days of observing them.

The source publishes one semicolon-separated, latin-1 encoded text file per plant, per reporter
group and per period, under
https://opendata.dwd.de/climate_environment/CDC/observations_germany/phenology/. A row is
``Stations_id;Referenzjahr;Qualitaetsniveau;Objekt_id;Phase_id;Eintrittsdatum;Eintrittsdatum_QB;Jultag``.

That file layout is what the model follows: one **dataset per plant** (all of its phases arrive
in one file) and one **parameter per phenological phase**. A value is ``Jultag``, the day of the
year the phase was reached, dated to the 1st of January of ``Referenzjahr`` at the ``annual``
resolution; ``quality`` carries ``Qualitaetsniveau``. A parameter's ``name_original`` is the
numeric ``Phase_id``, which is the only name the data files themselves use for a phase.

The plant and phase tables below are transcribed from the descriptions DWD publishes beside the
data -- ``PH_Beschreibung_Pflanze.txt`` and ``PH_Beschreibung_Phase.txt`` in
https://opendata.dwd.de/climate_environment/CDC/help/, and the per-group
``PH_Beschreibung_Phasendefinition_*.txt`` for which phases each plant is observed for. Two
typos in DWD's English column are corrected ("unfoalding", "mil ripeness"), and phase 68
(``Knospenschwellen``) is named from the immediate reporters' phase definitions, which is the
only place DWD lists it. ``tests/provider/dwd/phenology/test_api.py`` checks the tables here
against those files.
"""

from __future__ import annotations

from wetterdienst.model.metadata import build_metadata_model
from wetterdienst.provider.dwd.metadata import _METADATA

# The two reporter groups, as ``directory: (dataset name prefix, prose name)``. The prefix keeps
# the two apart where they observe the same plant, which most of them do.
_REPORTERS = {
    "annual_reporters": ("annual", "annual reporters (Jahresmelder)"),
    "immediate_reporters": ("immediate", "immediate reporters (Sofortmelder)"),
}

# ``Phase_id`` -> (canonical parameter name, DWD's German phase name, DWD's English phase name).
_PHASES: dict[int, tuple[str, str, str]] = {
    1: ("phenology_turning_green_beginning", "Ergrünen Beginn", "beginning of turning green"),
    2: ("phenology_bleeding_first", "Erstes Bluten", "first bleeding of the vines"),
    3: ("phenology_sprouting_beginning", "Austrieb Beginn", "sprouting of leaves"),
    4: ("phenology_leaf_unfolding_beginning", "Blattentfaltung Beginn", "beginning of unfolding of leaves"),
    5: ("phenology_flowering_beginning", "Blüte Beginn", "beginning of flowering"),
    6: ("phenology_flowering_general", "Vollblüte", "general flowering"),
    7: ("phenology_flowering_end", "Blüte Ende", "end of flowering"),
    8: ("phenology_may_sprouting", "Maitrieb", "beginning of may sprouting"),
    9: ("phenology_st_johns_sprouting", "Johannistrieb", "St. John's sprout"),
    10: ("phenology_sowing_beginning", "Bestellung Beginn", "beginning of tilling sowing drilling"),
    11: ("phenology_planting_beginning", "Pflanzen Beginn", "beginning of planting"),
    12: ("phenology_emergence_beginning", "Auflaufen Beginn", "beginning of emergence"),
    13: ("phenology_stand_closed", "Bestand geschlossen", "closed stand"),
    14: ("phenology_rosette_formation_beginning", "Rosettenbildung Beginn", "beginning of rosette formation"),
    15: ("phenology_shooting_beginning", "Schossen Beginn", "beginning of shooting"),
    16: ("phenology_leaf_formation_beginning", "Blattbildung Beginn", "beginning of formation of leaves"),
    17: ("phenology_bud_formation_beginning", "Knospenbildung Beginn", "beginning of bud formation"),
    18: ("phenology_heading_beginning", "Ährenschieben Beginn", "beginning of heading"),
    19: ("phenology_milk_ripeness_beginning", "Milchreife Beginn", "beginning of milk ripeness"),
    20: ("phenology_dough_ripeness_beginning", "Teigreife Beginn", "beginning of wax-ripe stage"),
    21: ("phenology_yellow_ripeness_beginning", "Gelbreife Beginn", "yellow ripeness"),
    22: ("phenology_full_ripeness_beginning", "Vollreife Beginn", "beginning of full ripeness"),
    23: ("phenology_harvest_by_hand", "Ernte von Hand", "hand harvest"),
    24: ("phenology_harvest", "Ernte", "harvest"),
    25: ("phenology_hay_cut_first", "1. Heuschnitt", "first cut for hay"),
    26: ("phenology_silage_cut_first", "1. Silageschnitt", "first cut for silage"),
    27: ("phenology_hay_cut_second", "2. Heuschnitt", "second cut for hay"),
    28: ("phenology_silage_cut_second", "2. Silageschnitt", "second cut for silage"),
    29: ("phenology_picking_ripeness_beginning", "Pflückreife Beginn", "fruit ripe for picking"),
    30: ("phenology_grape_harvest", "Lese", "grape harvest"),
    31: ("phenology_leaf_colouring_autumn", "herbstliche Blattverfärbung", "autumn colouring of leaves"),
    32: ("phenology_leaf_fall_autumn", "herbstlicher Blattfall", "autumn leave fall"),
    33: ("phenology_activity_beginning", "Beginn", "beginning"),
    34: ("phenology_activity_end", "Ende", "ending"),
    35: ("phenology_hay_or_silage_cut_first", "1. Heu- oder (!) Silageschnitt", "first cut for hay or silage"),
    36: ("phenology_hay_or_silage_cut_second", "2. Heu- oder (!) Silageschnitt", "second cut for hay or silage"),
    37: ("phenology_silk_emergence_beginning", "Narbenfädenschieben Beginn", "beginning of silk emergence"),
    38: ("phenology_grain_harvest_beginning", "Körner-Ernte Beginn", "grain harvest"),
    39: ("phenology_silage_harvest_beginning", "Silo-Ernte Beginn", "silage harvest"),
    40: ("phenology_grape_picking_ripeness", "Lesereife", "grapes ripe for picking"),
    41: (
        "phenology_flowering_end_observation_area",
        "Blüte Ende im Beobachtungsgebiet",
        "end of flowering in the observation area",
    ),
    42: ("phenology_grape_ripeness_beginning", "Reife Beginn Weinrebe", "beginning of ripeness of grapes"),
    61: ("phenology_needle_unfolding_beginning", "Nadelentfaltung Beginn", "beginning of unfolding of needles"),
    62: ("phenology_fruit_ripe_first", "erste reife Früchte", "first ripe fruit"),
    63: ("phenology_needle_colouring_autumn", "herbstliche Nadelverfärbung", "autumn colouring of needles"),
    64: ("phenology_needle_fall_autumn", "herbstlicher Nadelfall", "autumn needle fall"),
    65: ("phenology_tassel_tip_visible", "Fahnenschieben Beginn", "tip of tassel visible"),
    66: ("phenology_panicle_emergence_beginning", "Rispenschieben Beginn", "beginning tassel emergence"),
    67: ("phenology_height_growth_beginning", "Längenwachstum Beginn", "beginning of growth in height"),
    68: ("phenology_bud_swelling", "Knospenschwellen", "bud swelling"),
}

# ``Objekt_id`` -> (DWD German name, DWD English name, botanical name). The botanical name is
# empty where DWD gives none, i.e. for the grassland and farming-activity objects.
_OBJECTS: dict[int, tuple[str, str, str]] = {
    25: ("Rüben", "beet", "Beta vulgaris"),
    101: ("Beifuß", "common wormwood", "Artemisia vulgaris"),
    102: ("Busch-Windröschen", "wood anemone", "Anemone nemorosa"),
    103: ("Eberesche", "rowan", "Sorbus aucuparia"),
    104: ("Esche", "ash", "Fraxinus excelsior"),
    105: ("Europäische Lärche", "European larch", "Larix decidua"),
    107: ("Fichte", "Norway spruce", "Picea abies"),
    108: ("Flieder", "lilac", "Syringa vulgaris"),
    109: ("Forsythie", "forsythia", "Forsythia suspensa"),
    111: ("Birke (alle Arten)", "birch (all species)", "Betula"),
    112: ("Hänge-Birke", "silver birch", "Betula alba"),
    113: ("Hasel", "common hazel", "Corylus avellana"),
    114: ("Heidekraut", "common heather", "Calluna vulgaris"),
    115: ("Herbstzeitlose", "autumn crocus", "Colchicum autumnale"),
    116: ("Huflattich", "coltsfoot", "Tussilago farfara"),
    117: ("Hunds-Rose", "dog rose", "Rosa canina"),
    118: ("Kiefer", "Scots pine", "Pinus sylvestris"),
    119: ("Kornelkirsche", "cornelian cherry", "Cornus mas"),
    120: ("Löwenzahn", "dandelion", "Taraxacum officinale"),
    121: ("Robinie", "black locust", "Robinia pseudoacacia"),
    122: ("Rosskastanie", "horse chestnut", "Aesculus hippocastanum"),
    123: ("Rotbuche", "European beech", "Fagus sylvatica"),
    124: ("Sal-Weide", "goat willow", "Salix caprea"),
    125: ("Schlehe", "blackthorn", "Prunus spinosa"),
    127: ("Schneeglöckchen", "common snowdrop", "Galanthus nivalis"),
    128: ("Schwarz-Erle", "European alder", "Alnus glutinosa"),
    129: ("Schwarzer Holunder", "black elder", "Sambucus nigra"),
    130: ("Sommer-Linde", "large leaved lime", "Tilia platyphyllos"),
    131: ("Spitz-Ahorn", "Norway maple", "Acer platanoides"),
    132: ("Stiel-Eiche", "pedunculate oak", "Quercus robur"),
    133: ("Tanne", "white fir", "Abies alba"),
    134: ("Traubenkirsche", "hackberry", "Prunus padus"),
    135: ("Wiesen-Fuchsschwanz", "meadow foxtail", "Alopecurus pratensis"),
    136: ("Wiesen-Knäuelgras", "orchard grass", "Dactylis glomerata"),
    137: ("Winter-Linde", "small leafed lime", "Tilia cordata"),
    138: ("Zweigriffliger Weißdorn", "midland hawthorn", "Crataegus laevigata"),
    139: ("Erle (alle Arten)", "alder (all species)", "Alnus"),
    201: ("Dauergrünland", "meadows", ""),
    202: ("Winterweizen", "winter wheat", "Triticum aestivum"),
    203: ("Winterroggen", "winter rye", "Secale cereale"),
    204: ("Wintergerste", "winter barley", "Hordeum vulgare"),
    205: ("Winterraps", "winter oilseed rape", "Brassica napus var. napus"),
    206: ("Sommerweizen", "spring wheat", "Triticum aestivum"),
    207: ("Sommergerste", "spring barley", "Hordeum vulgare"),
    208: ("Hafer", "oat", "Avena sativa"),
    209: ("Sonnenblume", "sunflower", "Helianthus annuus"),
    210: ("Mais (ohne Sortenangabe)", "maize (without variety specification)", "Zea mays"),
    215: ("Mais", "maize", "Zea mays"),
    231: ("Kartoffel", "potato", "Solanum tuberosum"),
    243: ("Tomate", "tomato", "Solanum lycopersicum"),
    244: ("Weißkohl", "white cabbage", "Brassica oleracea var. capitata f. alba"),
    250: ("Sorte unbekannt (Rübe)", "beet", "Beta vulgaris"),
    252: ("Futter-Rübe", "fodder beet", "Beta vulgaris var. crassa"),
    253: ("Zucker-Rübe", "sugar beet", "Beta vulgaris var. altissima"),
    310: ("Apfel", "apple", "Malus domestica"),
    311: ("Apfel, frühe Reife", "apple (early ripeness)", "Malus domestica"),
    313: ("Apfel, späte Reife", "apple (late ripeness)", "Malus domestica"),
    320: ("Birne", "pear", "Pyrus communis"),
    321: ("Birne, frühe Reife", "pear (early ripeness)", "Pyrus communis"),
    322: ("Birne, späte Reife", "pear (late ripeness)", "Pyrus communis"),
    330: ("Süßkirsche", "cherry", "Prunus avium"),
    331: ("Süßkirsche, frühe Reife", "cherry (early ripeness)", "Prunus avium"),
    332: ("Süßkirsche, späte Reife", "cherry (late ripeness)", "Prunus avium"),
    340: ("Sauerkirsche", "morello", "Prunus cerasus"),
    350: ("Stachelbeere", "gooseberry", "Ribes uva-crispa"),
    360: ("Rote Johannisbeere", "red currant", "Ribes rubrum"),
    361: ("Johannisbeere, alle Sorten", "currant (all varieties)", "Ribes sylvestris"),
    371: ("Pflaume, frühe Reife", "plum (early ripeness)", "Prunus domestica"),
    372: ("Pflaume, späte Reife", "plum (late ripeness)", "Prunus domestica"),
    410: ("Weinrebe", "vine", "Vitis vinifera"),
    411: ("Weinrebe, frühe Reife", "vine (early ripeness)", "Vitis vinifera"),
    412: (
        "Weinrebe, mittelspäte Reife (bevorzugt Silvaner/Weißburgunder)",
        "vine (middle-late ripeness - Silvaner/Pinot Blanc preferred)",
        "Vitis vinifera",
    ),
    413: ("Weinrebe, späte Reife", "vine (late ripeness)", "Vitis vinifera"),
    414: (
        "Weinrebe, blaue Trauben (bevorzugt Portugieser/Spätburgunder)",
        "vine (blue grapes - Portugieser/Pinot Noir preferred))",
        "Vitis vinifera",
    ),
    501: ("Feldarbeit", "farming", ""),
    601: ("Weidegang", "cattle on the pastures", ""),
    4111: ("Müller-Thurgau", "vine (Müller-Thurgau)", "Vitis vinifera"),
}

# One entry per source file: (reporter directory, group directory, file stem, dataset name
# without the reporter prefix, ``Objekt_id``, periods that publish it, ``Phase_id``s observed).
# The file stem is the name without the ``_akt.txt`` / ``_<from>_<to>_hist.txt`` suffix that the
# period adds. A few plants are published for one period only: those discontinued before the
# recent files begin have no ``recent``, and two added since the last historical release have no
# ``historical``.
_PLANTS: tuple[tuple[str, str, str, str, int, tuple[str, ...], tuple[int, ...]], ...] = (
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Ruebe",
        "beet",
        25,
        ("recent",),
        (10, 12, 13, 24),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Rueben_ohne_Sortenangabe",
        "beet_unspecified_variety",
        250,
        ("historical", "recent"),
        (10, 12, 13, 24),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Futter-Ruebe",
        "fodder_beet",
        252,
        ("historical", "recent"),
        (10, 12, 13, 24),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Mais",
        "maize",
        215,
        ("historical", "recent"),
        (5, 6, 10, 12, 19, 20, 21, 24, 65, 67),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Hafer",
        "oat",
        208,
        ("historical", "recent"),
        (10, 12, 15, 19, 21, 22, 23, 24, 66),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Dauergruenland",
        "permanent_grassland",
        201,
        ("historical", "recent"),
        (1, 25, 26, 27, 28, 35, 36),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Sommergerste",
        "spring_barley",
        207,
        ("historical", "recent"),
        (10, 12, 15, 18, 21, 22, 23, 24),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Sommerweizen",
        "spring_wheat",
        206,
        ("historical",),
        (10, 12, 15, 18, 21, 22, 23, 24),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Zucker-Ruebe",
        "sugar_beet",
        253,
        ("historical", "recent"),
        (10, 12, 13, 24),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Sonnenblume",
        "sunflower",
        209,
        ("historical", "recent"),
        (5, 10, 12, 16, 17, 24),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Tomate",
        "tomato",
        243,
        ("historical",),
        (5, 11, 24),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Weisskohl",
        "white_cabbage",
        244,
        ("historical",),
        (11, 24),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Wintergerste",
        "winter_barley",
        204,
        ("historical", "recent"),
        (10, 12, 15, 18, 21, 22, 23, 24),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Winterraps",
        "winter_oilseed_rape",
        205,
        ("historical", "recent"),
        (5, 10, 12, 14, 17, 22, 23, 24, 67),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Winterroggen",
        "winter_rye",
        203,
        ("historical", "recent"),
        (5, 6, 10, 12, 15, 18, 21, 22, 23, 24),
    ),
    (
        "annual_reporters",
        "crops",
        "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Winterweizen",
        "winter_wheat",
        202,
        ("historical", "recent"),
        (10, 12, 15, 18, 19, 21, 22, 23, 24),
    ),
    ("annual_reporters", "farming", "PH_Jahresmelder_Feldarbeit_Feldarbeit", "field_work", 501, ("historical",), (33,)),
    ("annual_reporters", "farming", "PH_Jahresmelder_Weidegang_Weidegang", "grazing", 601, ("historical",), (33, 34)),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Apfel",
        "apple",
        310,
        ("historical", "recent"),
        (3, 5, 6, 7, 29, 32),
    ),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Apfel_fruehe_Reife",
        "apple_early_ripening",
        311,
        ("historical", "recent"),
        (3, 5, 6, 7, 29, 32),
    ),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Apfel_spaete_Reife",
        "apple_late_ripening",
        313,
        ("historical", "recent"),
        (3, 5, 6, 7, 29, 32),
    ),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Johannisbeere_alle_Sorten",
        "currant_all_varieties",
        361,
        ("recent",),
        (5, 29),
    ),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Stachelbeere",
        "gooseberry",
        350,
        ("historical", "recent"),
        (3, 4, 5, 29),
    ),
    ("annual_reporters", "fruit", "PH_Jahresmelder_Obst_Birne", "pear", 320, ("historical", "recent"), (5, 6, 7, 29)),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Birne_fruehe_Reife",
        "pear_early_ripening",
        321,
        ("historical", "recent"),
        (5, 6, 7, 29),
    ),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Birne_spaete_Reife",
        "pear_late_ripening",
        322,
        ("historical", "recent"),
        (5, 6, 7, 29),
    ),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Pflaume_fruehreifend",
        "plum_early_ripening",
        371,
        ("historical", "recent"),
        (29,),
    ),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Pflaume_spaetreifend",
        "plum_late_ripening",
        372,
        ("historical",),
        (29,),
    ),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Rote_Johannisbeere",
        "red_currant",
        360,
        ("historical", "recent"),
        (5, 29),
    ),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Sauerkirsche",
        "sour_cherry",
        340,
        ("historical", "recent"),
        (5, 6, 7, 29),
    ),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Suesskirsche",
        "sweet_cherry",
        330,
        ("historical", "recent"),
        (5, 6, 7, 29, 31),
    ),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Suesskirsche_fruehe_Reife",
        "sweet_cherry_early_ripening",
        331,
        ("historical", "recent"),
        (5, 6, 7, 29, 31),
    ),
    (
        "annual_reporters",
        "fruit",
        "PH_Jahresmelder_Obst_Suesskirsche_spaete_Reife",
        "sweet_cherry_late_ripening",
        332,
        ("historical", "recent"),
        (5, 6, 7, 29, 31),
    ),
    (
        "annual_reporters",
        "vine",
        "PH_Jahresmelder_Weinrebe_Weinrebe",
        "grapevine",
        410,
        ("historical",),
        (3, 5, 6, 7, 30, 31, 32, 42),
    ),
    (
        "annual_reporters",
        "vine",
        "PH_Jahresmelder_Weinrebe_Weinrebe_blaue_Trauben",
        "grapevine_blue_grapes",
        414,
        ("historical",),
        (30, 32),
    ),
    (
        "annual_reporters",
        "vine",
        "PH_Jahresmelder_Weinrebe_Weinrebe_fruehe_Reife",
        "grapevine_early_ripening",
        411,
        ("historical", "recent"),
        (2, 3, 4, 5, 6, 7, 30, 31, 32, 42),
    ),
    (
        "annual_reporters",
        "vine",
        "PH_Jahresmelder_Weinrebe_Weinrebe_spaete_Reife",
        "grapevine_late_ripening",
        413,
        ("historical", "recent"),
        (2, 3, 4, 5, 6, 7, 30, 31, 32, 42),
    ),
    (
        "annual_reporters",
        "vine",
        "PH_Jahresmelder_Weinrebe_Weinrebe_mittelspaete_Reife",
        "grapevine_middle_late_ripening",
        412,
        ("historical",),
        (30, 32),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Esche",
        "ash",
        104,
        ("historical", "recent"),
        (4, 5),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Herbstzeitlose",
        "autumn_crocus",
        115,
        ("historical", "recent"),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Traubenkirsche",
        "bird_cherry",
        134,
        ("historical",),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Schwarz-Erle",
        "black_alder",
        128,
        ("historical", "recent"),
        (4, 5),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Schwarzer_Holunder",
        "black_elder",
        129,
        ("historical", "recent"),
        (5, 62),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Robinie",
        "black_locust",
        121,
        ("historical", "recent"),
        (4, 5),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Schlehe",
        "blackthorn",
        125,
        ("historical", "recent"),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Huflattich",
        "coltsfoot",
        116,
        ("historical", "recent"),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Hasel",
        "common_hazel",
        113,
        ("historical", "recent"),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Heidekraut",
        "common_heather",
        114,
        ("historical", "recent"),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Schneegloeckchen",
        "common_snowdrop",
        127,
        ("historical", "recent"),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Beifuss",
        "common_wormwood",
        101,
        ("historical", "recent"),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Kornelkirsche",
        "cornelian_cherry",
        119,
        ("historical", "recent"),
        (5, 62),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Loewenzahn",
        "dandelion",
        120,
        ("historical", "recent"),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Hunds-Rose",
        "dog_rose",
        117,
        ("historical", "recent"),
        (5, 62),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Rotbuche",
        "european_beech",
        123,
        ("historical", "recent"),
        (4, 5, 31, 32, 62),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Europaeische-Laerche",
        "european_larch",
        105,
        ("historical", "recent"),
        (5, 61, 63, 64),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Forsythie",
        "forsythia",
        109,
        ("historical", "recent"),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Sal-Weide",
        "goat_willow",
        124,
        ("historical", "recent"),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Rosskastanie",
        "horse_chestnut",
        122,
        ("historical", "recent"),
        (3, 4, 5, 31, 32, 62),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Sommer-Linde",
        "large_leaved_lime",
        130,
        ("historical", "recent"),
        (4, 5),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Flieder",
        "lilac",
        108,
        ("historical", "recent"),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Wiesen-Fuchsschwanz",
        "meadow_foxtail",
        135,
        ("historical", "recent"),
        (5, 6),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Zweigriffliger_Weissdorn",
        "midland_hawthorn",
        138,
        ("historical", "recent"),
        (5, 62),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Spitz-Ahorn",
        "norway_maple",
        131,
        ("historical", "recent"),
        (5,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Fichte",
        "norway_spruce",
        107,
        ("historical", "recent"),
        (5, 8),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Wiesen-Knaeuelgras",
        "orchard_grass",
        136,
        ("historical", "recent"),
        (6,),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Stiel-Eiche",
        "pedunculate_oak",
        132,
        ("historical", "recent"),
        (4, 5, 9, 31, 32, 62),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Eberesche",
        "rowan",
        103,
        ("historical", "recent"),
        (3, 4, 5, 32, 62),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Kiefer",
        "scots_pine",
        118,
        ("historical", "recent"),
        (5, 8),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Haenge-Birke",
        "silver_birch",
        112,
        ("historical", "recent"),
        (3, 4, 5, 31, 32),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Tanne",
        "silver_fir",
        133,
        ("historical", "recent"),
        (5, 8),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Winter-Linde",
        "small_leaved_lime",
        137,
        ("historical", "recent"),
        (4, 5),
    ),
    (
        "annual_reporters",
        "wild",
        "PH_Jahresmelder_Wildwachsende_Pflanze_Busch-Windroeschen",
        "wood_anemone",
        102,
        ("historical", "recent"),
        (5,),
    ),
    (
        "immediate_reporters",
        "crops",
        "PH_Sofortmelder_Landwirtschaft_Kulturpflanze_Ruebe",
        "beet",
        25,
        ("historical", "recent"),
        (10, 12, 13),
    ),
    (
        "immediate_reporters",
        "crops",
        "PH_Sofortmelder_Landwirtschaft_Kulturpflanze_Mais_ohne_Sortenangabe",
        "maize_unspecified_variety",
        210,
        ("historical", "recent"),
        (5, 10, 12, 19, 20, 22, 37, 38, 39, 65),
    ),
    (
        "immediate_reporters",
        "crops",
        "PH_Sofortmelder_Landwirtschaft_Kulturpflanze_Hafer",
        "oat",
        208,
        ("historical", "recent"),
        (10, 12, 15, 21, 22, 24, 66),
    ),
    (
        "immediate_reporters",
        "crops",
        "PH_Sofortmelder_Landwirtschaft_Kulturpflanze_Dauergruenland",
        "permanent_grassland",
        201,
        ("historical", "recent"),
        (1, 25, 26, 27, 28, 35, 36),
    ),
    (
        "immediate_reporters",
        "crops",
        "PH_Sofortmelder_Landwirtschaft_Kulturpflanze_Kartoffel",
        "potato",
        231,
        ("historical", "recent"),
        (5, 10, 12, 13, 24),
    ),
    (
        "immediate_reporters",
        "crops",
        "PH_Sofortmelder_Landwirtschaft_Kulturpflanze_Sommergerste",
        "spring_barley",
        207,
        ("historical", "recent"),
        (10, 12, 15, 18, 21, 24),
    ),
    (
        "immediate_reporters",
        "crops",
        "PH_Sofortmelder_Landwirtschaft_Kulturpflanze_Wintergerste",
        "winter_barley",
        204,
        ("historical", "recent"),
        (10, 12, 15, 18, 21, 22, 24),
    ),
    (
        "immediate_reporters",
        "crops",
        "PH_Sofortmelder_Landwirtschaft_Kulturpflanze_Winterraps",
        "winter_oilseed_rape",
        205,
        ("historical", "recent"),
        (5, 7, 10, 12, 17, 22, 24, 67),
    ),
    (
        "immediate_reporters",
        "crops",
        "PH_Sofortmelder_Landwirtschaft_Kulturpflanze_Winterroggen",
        "winter_rye",
        203,
        ("historical", "recent"),
        (5, 6, 10, 12, 15, 18, 21, 24, 41),
    ),
    (
        "immediate_reporters",
        "crops",
        "PH_Sofortmelder_Landwirtschaft_Kulturpflanze_Winterweizen",
        "winter_wheat",
        202,
        ("historical", "recent"),
        (10, 12, 15, 18, 21, 22, 24),
    ),
    (
        "immediate_reporters",
        "fruit",
        "PH_Sofortmelder_Obst_Apfel",
        "apple",
        310,
        ("historical", "recent"),
        (3, 5, 7, 29, 41),
    ),
    (
        "immediate_reporters",
        "fruit",
        "PH_Sofortmelder_Obst_Apfel_spaete_Reife",
        "apple_late_ripening",
        313,
        ("historical", "recent"),
        (32,),
    ),
    (
        "immediate_reporters",
        "fruit",
        "PH_Sofortmelder_Obst_Stachelbeere",
        "gooseberry",
        350,
        ("historical", "recent"),
        (4,),
    ),
    (
        "immediate_reporters",
        "fruit",
        "PH_Sofortmelder_Obst_Rote_Johannisbeere",
        "red_currant",
        360,
        ("historical", "recent"),
        (29,),
    ),
    (
        "immediate_reporters",
        "fruit",
        "PH_Sofortmelder_Obst_Suesskirsche",
        "sweet_cherry",
        330,
        ("historical", "recent"),
        (5, 29),
    ),
    (
        "immediate_reporters",
        "vine",
        "PH_Sofortmelder_Weinrebe_Weinrebe_fruehe_Reife",
        "grapevine_early_ripening",
        411,
        ("historical",),
        (2, 4, 5, 6, 30, 40, 42),
    ),
    (
        "immediate_reporters",
        "vine",
        "PH_Sofortmelder_Weinrebe_Weinrebe_spaete_Reife",
        "grapevine_late_ripening",
        413,
        ("historical",),
        (2, 4, 5, 6, 30, 40, 42),
    ),
    (
        "immediate_reporters",
        "vine",
        "PH_Sofortmelder_Wein_Mueller-Thurgau",
        "grapevine_mueller_thurgau",
        4111,
        ("historical",),
        (2, 4, 5, 6, 30, 42),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Erle_alleArten",
        "alder_all_species",
        139,
        ("historical", "recent"),
        (5, 41),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Esche",
        "ash",
        104,
        ("historical", "recent"),
        (5,),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Birke_alleArten",
        "birch_all_species",
        111,
        ("historical", "recent"),
        (5, 41),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Schwarz-Erle",
        "black_alder",
        128,
        ("historical",),
        (5,),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Schwarzer_Holunder",
        "black_elder",
        129,
        ("historical", "recent"),
        (5, 62),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Robinie",
        "black_locust",
        121,
        ("historical", "recent"),
        (5,),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Schlehe",
        "blackthorn",
        125,
        ("historical",),
        (5,),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Huflattich",
        "coltsfoot",
        116,
        ("historical", "recent"),
        (5,),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Hasel",
        "common_hazel",
        113,
        ("historical", "recent"),
        (5, 41),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Schneegloeckchen",
        "common_snowdrop",
        127,
        ("historical", "recent"),
        (5,),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Beifuss",
        "common_wormwood",
        101,
        ("historical", "recent"),
        (5,),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Loewenzahn",
        "dandelion",
        120,
        ("historical", "recent"),
        (5,),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Rotbuche",
        "european_beech",
        123,
        ("historical", "recent"),
        (4, 5, 31, 32, 62),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Forsythie",
        "forsythia",
        109,
        ("historical", "recent"),
        (5,),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Sal-Weide",
        "goat_willow",
        124,
        ("historical", "recent"),
        (5,),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Rosskastanie",
        "horse_chestnut",
        122,
        ("historical", "recent"),
        (62,),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Sommer-Linde",
        "large_leaved_lime",
        130,
        ("historical", "recent"),
        (5,),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Wiesen-Fuchsschwanz",
        "meadow_foxtail",
        135,
        ("historical", "recent"),
        (5, 6),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Stiel-Eiche",
        "pedunculate_oak",
        132,
        ("historical", "recent"),
        (4, 31, 32, 62, 68),
    ),
    (
        "immediate_reporters",
        "wild",
        "PH_Sofortmelder_Wildwachsende_Pflanze_Haenge-Birke",
        "silver_birch",
        112,
        ("historical", "recent"),
        (4, 5),
    ),
)


def _dataset(
    reporter: str,
    group: str,
    stem: str,
    plant: str,
    object_id: int,
    periods: tuple[str, ...],
    phases: tuple[int, ...],
) -> dict:
    """Build one dataset -- one plant, as published by one reporter group."""
    prefix, reporter_prose = _REPORTERS[reporter]
    german, english, botanical = _OBJECTS[object_id]
    subject = f"{german} ({english}, {botanical})" if botanical else f"{german} ({english})"
    return {
        "name": f"{prefix}_{plant}",
        # the path to the file, minus the period directory and the period-dependent suffix
        "name_original": f"{reporter}/{group}/{stem}",
        "grouped": True,
        "periods": list(periods),
        "date_required": False,
        "description": f"Phenological phases of {subject}, observed by the DWD {reporter_prose}.",
        "parameters": [
            {
                "name": _PHASES[phase][0],
                "name_original": str(phase),
                "unit": "dimensionless",
                "description": f"{_PHASES[phase][2].capitalize()} ({_PHASES[phase][1]}).",
            }
            for phase in phases
        ],
    }


DwdPhenologyMetadata = {
    **_METADATA,
    "copyright": "© Deutscher Wetterdienst (DWD), Climate Data Center (CDC), phenology",
    "url": "https://opendata.dwd.de/climate_environment/CDC/observations_germany/phenology/",
    "kind": "observation",
    "timezone": "Europe/Berlin",
    "resolutions": [
        {
            "name": "annual",
            "name_original": "annual",
            "periods": ["historical", "recent"],
            "date_required": False,
            "datasets": [_dataset(*plant) for plant in _PLANTS],
        },
    ],
}
DwdPhenologyMetadata = build_metadata_model(DwdPhenologyMetadata, "DwdPhenologyMetadata")

# ``dataset name -> Objekt_id``, so the values parser can drop any row that is not the plant the
# file is named for. Every file holds exactly one object today; the filter keeps that assumption
# from silently breaking.
DWD_PHENOLOGY_OBJECT_IDS: dict[str, int] = {
    f"{_REPORTERS[reporter][0]}_{plant}": object_id for reporter, _, _, plant, object_id, _, _ in _PLANTS
}

# ``dataset name -> (reporter directory, group directory, file stem)``, the three path parts the
# file index needs. Derived from ``name_original`` rather than kept a second time.
DWD_PHENOLOGY_PATHS: dict[str, tuple[str, str, str]] = {
    f"{_REPORTERS[reporter][0]}_{plant}": (reporter, group, stem) for reporter, group, stem, plant, _, _, _ in _PLANTS
}
