name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  OS: "ubuntu-latest"
  PYTHON: "3.14"
  WD_AUTH__METNO_FROST: ${{ secrets.WD_AUTH__METNO_FROST }}

permissions: {}

jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: codecov
    permissions:
      contents: read
    steps:
      - name: Acquire sources
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON }}

      - name: Install project
        run: uv sync

      - name: Install extras for testing
        run: .github/workflows/install.sh testing

      - name: Run tests, with coverage (parallel)
        run: uv run poe coverage:parallel

      - name: Run tests, with coverage (cflakes)
        if: always()
        run: uv run poe coverage:cflakes

      - name: Upload coverage report to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./junit-parallel.xml,./junit-cflakes.xml
          report_type: test_results
          fail_ci_if_error: false
