# Stage Docker images through GitHub Actions (GHA) to GitHub Container Registry (GHCR).
#
# Derived from:
# https://github.com/crate/cratedb-prometheus-adapter/blob/main/.github/workflows/release.yml
name: Release Docker Standard

permissions:
  contents: read
  packages: write
  id-token: write

on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '0 10 * * *' # everyday at 10am

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

# The name for the produced image at ghcr.io.
env:
  IMAGE_NAME: "${{ github.repository }}-standard"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64
          cache: poetry

      - name: Build wheel package
        run: poetry build --format=wheel

      - name: Upload wheel package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-wheel-${{ github.sha }}
          path: dist/wetterdienst-*.whl
          retention-days: 7

      - name: Run tests
        run: |
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1
          export BUILDKIT_PROGRESS=plain    
          if [[ -f .github/release/standard.test.yml ]]; then
            docker-compose --file .github/release/standard.test.yml build
            docker-compose --file .github/release/standard.test.yml run sut
          fi

  docker:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: ${{ ! (startsWith(github.actor, 'dependabot') || github.event.pull_request.head.repo.fork ) }}

    steps:
      - name: Acquire sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download wheel package
        uses: actions/download-artifact@v3
        with:
          name: ${{ runner.os }}-wheel-${{ github.sha }}
          path: dist

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # List of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
          # Generate Docker tags based on the following events/attributes
          tags: |
            type=schedule,pattern=nightly
            type=ref,event=pr
            type=semver,pattern={{version}},enable=${{ github.event_name == 'push' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'push' }}
            type=sha

      - name: Inspect meta
        run: |
          echo "Tags:      ${{ steps.meta.outputs.tags }}"
          echo "Labels:    ${{ steps.meta.outputs.labels }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/release/standard/Dockerfile
          platforms: linux/amd64  # in future we might want to add: linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Display git status
        run: |
          set -x
          git describe --tags
          git status

  docker-sync:
    if: ${{ ! (startsWith(github.actor, 'dependabot') || github.event.pull_request.head.repo.fork) }}
    needs: [ docker]
    runs-on: ubuntu-latest
    steps:
      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Google Auth
        uses: google-github-actions/auth@v2
        env:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        with:
          workload_identity_provider: ${{ env.workload_identity_provider }}
          service_account: cicd-dev@wetterdienst.iam.gserviceaccount.com

      - name: Configure docker
        run: |
          gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Docker pull
        run: docker pull ghcr.io/${{ github.repository }}-standard:latest

      - name: Docker tag
        run: docker tag ghcr.io/earthobservations/wetterdienst-standard:latest europe-north1-docker.pkg.dev/wetterdienst/docker-wetterdienst/wetterdienst-standard:latest

      - name: Docker push
        run: docker push europe-north1-docker.pkg.dev/wetterdienst/docker-wetterdienst/wetterdienst-standard:latest
