name: Linter
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Acquire sources
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - name: Install test automation tools
      run: |
        pip install nox==2020.8.22
        pip install poetry==1.0.10
    - name: Run lint on code
      run: nox -s lint
