name: Linter
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run:
    runs-on: ubuntu-latest
    name: Code style checks
    steps:

    - name: Acquire sources
      uses: actions/checkout@v3

    - name: Setup Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Setup Python
      id: python-setup
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        architecture: x64
        cache: poetry

    - name: Install project tooling
      run: poetry install --no-interaction --no-root

    - name: Run code-style checks
      run: poetry run poe lint
