name: Linter
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run:
    runs-on: ubuntu-latest
    name: Code style checks
    steps:
    - name: Acquire sources
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        architecture: x64

    - name: Setup Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Get Poetry cache directory
      id: poetry-cache-dir
      run: |
        echo "::set-output name=dir::$(poetry config cache-dir)"

    - name: Apply cache
      id: poetry-cache-flag
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if `poetry.lock` has not changed.
        CACHE_NUMBER: 1
      with:
        path: ${{ steps.poetry-cache-dir.outputs.dir }}
        key: poetry-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}-${{ env.CACHE_NUMBER }}

    - name: Install library
      run: poetry install --no-root

    - name: Run lint on code
      run: poetry run poe lint
