name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  PYTHON: "3.14"

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Acquire sources
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: ${{ env.PYTHON }}

      - name: Install project
        run: uv sync

      - name: Run code-style checks
        run: uv run poe lint
